"""processing pathways

Revision ID: a47e05ecb5b2
Revises: 3d80ee69eedf
Create Date: 2026-09-26 15:22:10.040304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (used by JSONB variants in autogenerated code)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a47e05ecb5b2'
down_revision: Union[str, Sequence[str], None] = '3d80ee69eedf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_methods',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_material_id', sa.Uuid(), nullable=False),
    sa.Column('output_material_id', sa.Uuid(), nullable=False),
    sa.Column('processing_steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('input_constraints', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('output_properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_yield', sa.Float(), nullable=False),
    sa.Column('processing_time_days', sa.Integer(), nullable=False),
    sa.Column('indicative_cost_per_tonne', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('quality_requirements', sa.Text(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('expected_yield > 0 AND expected_yield <= 1', name=op.f('ck_processing_methods_yield_range')),
    sa.CheckConstraint('processing_time_days >= 0', name=op.f('ck_processing_methods_time_nonneg')),
    sa.ForeignKeyConstraint(['input_material_id'], ['materials.id'], name=op.f('fk_processing_methods_input_material_id_materials')),
    sa.ForeignKeyConstraint(['output_material_id'], ['materials.id'], name=op.f('fk_processing_methods_output_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_methods')),
    sa.UniqueConstraint('key', name=op.f('uq_processing_methods_key'))
    )
    with op.batch_alter_table('processing_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processing_methods_input_material_id'), ['input_material_id'], unique=False)

    op.create_table('processor_capabilities',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('method_id', sa.Uuid(), nullable=False),
    sa.Column('capacity_per_month', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('available_capacity_per_month', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('processing_cost_per_tonne', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_is_demo', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_input_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('available_capacity_per_month <= capacity_per_month', name=op.f('ck_processor_capabilities_available_le_capacity')),
    sa.CheckConstraint('available_capacity_per_month >= 0', name=op.f('ck_processor_capabilities_available_nonneg')),
    sa.CheckConstraint('capacity_per_month >= 0', name=op.f('ck_processor_capabilities_capacity_nonneg')),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_processor_capabilities_facility_id_facilities')),
    sa.ForeignKeyConstraint(['method_id'], ['processing_methods.id'], name=op.f('fk_processor_capabilities_method_id_processing_methods')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_processor_capabilities_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processor_capabilities'))
    )
    with op.batch_alter_table('processor_capabilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processor_capabilities_method_id'), ['method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processor_capabilities_organization_id'), ['organization_id'], unique=False)

    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_processed', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_column('is_processed')

    with op.batch_alter_table('processor_capabilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processor_capabilities_organization_id'))
        batch_op.drop_index(batch_op.f('ix_processor_capabilities_method_id'))

    op.drop_table('processor_capabilities')
    with op.batch_alter_table('processing_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processing_methods_input_material_id'))

    op.drop_table('processing_methods')
    # ### end Alembic commands ###
