"""matching and assessment

Revision ID: e2d9d6f7b42a
Revises: cc1c821737a2
Create Date: 2026-09-26 11:29:52.068402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (used by JSONB variants in autogenerated code)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2d9d6f7b42a'
down_revision: Union[str, Sequence[str], None] = 'cc1c821737a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emission_factors',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('scope', sa.Enum('TRANSPORT', 'VIRGIN_PRODUCTION', 'DISPOSAL', 'PROCESSING', name='factorscope', native_enum=False, length=32), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('application_type_id', sa.Uuid(), nullable=True),
    sa.Column('disposition', sa.String(length=32), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('geography', sa.String(length=80), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('is_demo_value', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('valid_until IS NULL OR valid_until >= valid_from', name=op.f('ck_emission_factors_validity_order')),
    sa.CheckConstraint('value >= 0', name=op.f('ck_emission_factors_value_nonneg')),
    sa.ForeignKeyConstraint(['application_type_id'], ['application_types.id'], name=op.f('fk_emission_factors_application_type_id_application_types')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_emission_factors_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_emission_factors'))
    )
    with op.batch_alter_table('emission_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emission_factors_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_emission_factors_scope'), ['scope'], unique=False)

    op.create_table('matching_configs',
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_matching_configs_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matching_configs')),
    sa.UniqueConstraint('version', name=op.f('uq_matching_configs_version'))
    )
    with op.batch_alter_table('matching_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matching_configs_is_active'), ['is_active'], unique=False)

    op.create_table('matches',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('provider_org_id', sa.Uuid(), nullable=False),
    sa.Column('demander_org_id', sa.Uuid(), nullable=False),
    sa.Column('matching_version', sa.String(length=32), nullable=False),
    sa.Column('methodology_version', sa.String(length=64), nullable=False),
    sa.Column('material_score', sa.Float(), nullable=False),
    sa.Column('quantity_score', sa.Float(), nullable=False),
    sa.Column('location_score', sa.Float(), nullable=True),
    sa.Column('timing_score', sa.Float(), nullable=False),
    sa.Column('processing_score', sa.Float(), nullable=False),
    sa.Column('economic_score', sa.Float(), nullable=True),
    sa.Column('environmental_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidencelevel', native_enum=False, length=32), nullable=False),
    sa.Column('feasibility', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='feasibility', native_enum=False, length=32), nullable=False),
    sa.Column('requires_manual_review', sa.Boolean(), nullable=False),
    sa.Column('match_type', sa.Enum('EXACT_MATERIAL', 'APPLICATION', 'CATEGORY', 'SEMANTIC', name='matchtype', native_enum=False, length=32), nullable=False),
    sa.Column('is_hidden_match', sa.Boolean(), nullable=False),
    sa.Column('distance_km', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('demand_coverage', sa.Float(), nullable=False),
    sa.Column('supply_utilization', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('assessment_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'VIEWED', 'INTERESTED', 'CONNECTION_REQUESTED', 'CONNECTED', 'NEGOTIATING', 'ACTIVE_EXCHANGE', 'COMPLETED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='matchstatus', native_enum=False, length=32), nullable=False),
    sa.Column('stale_reason', sa.String(length=255), nullable=True),
    sa.Column('rejected_by_org_id', sa.Uuid(), nullable=True),
    sa.Column('provider_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demander_viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('provider_interested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('demander_interested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('overall_score >= 0 AND overall_score <= 1', name=op.f('ck_matches_overall_range')),
    sa.CheckConstraint('provider_org_id <> demander_org_id', name=op.f('ck_matches_distinct_orgs')),
    sa.ForeignKeyConstraint(['demander_org_id'], ['organizations.id'], name=op.f('fk_matches_demander_org_id_organizations')),
    sa.ForeignKeyConstraint(['provider_org_id'], ['organizations.id'], name=op.f('fk_matches_provider_org_id_organizations')),
    sa.ForeignKeyConstraint(['rejected_by_org_id'], ['organizations.id'], name=op.f('fk_matches_rejected_by_org_id_organizations')),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_matches_requirement_id_requirements')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_matches_resource_id_resources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('resource_id', 'requirement_id', name='uq_match_pair')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index('ix_matches_demander_status', ['demander_org_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_overall_score'), ['overall_score'], unique=False)
        batch_op.create_index('ix_matches_provider_status', ['provider_org_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matches_status'))
        batch_op.drop_index(batch_op.f('ix_matches_resource_id'))
        batch_op.drop_index(batch_op.f('ix_matches_requirement_id'))
        batch_op.drop_index('ix_matches_provider_status')
        batch_op.drop_index(batch_op.f('ix_matches_overall_score'))
        batch_op.drop_index(batch_op.f('ix_matches_expires_at'))
        batch_op.drop_index('ix_matches_demander_status')

    op.drop_table('matches')
    with op.batch_alter_table('matching_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matching_configs_is_active'))

    op.drop_table('matching_configs')
    with op.batch_alter_table('emission_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emission_factors_scope'))
        batch_op.drop_index(batch_op.f('ix_emission_factors_key'))

    op.drop_table('emission_factors')
    # ### end Alembic commands ###
