"""core domain

Revision ID: cc1c821737a2
Revises: 
Create Date: 2026-09-26 11:11:13.418430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc1c821737a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_types',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applicable_industry_sectors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_types')),
    sa.UniqueConstraint('key', name=op.f('uq_application_types_key'))
    )
    op.create_table('locations',
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=80), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name=op.f('ck_locations_latitude_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name=op.f('ck_locations_longitude_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations'))
    )
    op.create_table('materials',
    sa.Column('canonical_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('subcategory', sa.String(length=80), nullable=True),
    sa.Column('physical_state', sa.Enum('SOLID', 'LIQUID', 'GAS', 'SLUDGE', 'ENERGY', 'OTHER', name='physicalstate', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials')),
    sa.UniqueConstraint('canonical_name', name=op.f('uq_materials_canonical_name'))
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_materials_subcategory'), ['subcategory'], unique=False)

    op.create_table('property_definitions',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('data_type', sa.Enum('NUMERIC', 'TEXT', 'BOOLEAN', name='propertydatatype', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('valid_min', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('valid_max', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_property_definitions')),
    sa.UniqueConstraint('key', name=op.f('uq_property_definitions_key'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_platform_admin', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('material_applications',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('application_type_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['application_type_id'], ['application_types.id'], name=op.f('fk_material_applications_application_type_id_application_types'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_applications_material_id_materials'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_applications')),
    sa.UniqueConstraint('material_id', 'application_type_id', name='uq_material_application')
    )
    with op.batch_alter_table('material_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_applications_application_type_id'), ['application_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_applications_material_id'), ['material_id'], unique=False)

    op.create_table('material_properties',
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('typical_min', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('typical_max', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('typical_min IS NULL OR typical_max IS NULL OR typical_min <= typical_max', name=op.f('ck_material_properties_typical_range')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_properties_material_id_materials'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property_definitions.id'], name=op.f('fk_material_properties_property_id_property_definitions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_properties')),
    sa.UniqueConstraint('material_id', 'property_id', name='uq_material_property')
    )
    with op.batch_alter_table('material_properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_properties_material_id'), ['material_id'], unique=False)

    op.create_table('organizations',
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('industry_sector', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('business_email', sa.String(length=320), nullable=True),
    sa.Column('business_phone', sa.String(length=32), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='organizationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('operating_mode', sa.Enum('PROVIDER', 'DEMANDER', 'BOTH', name='operatingmode', native_enum=False, length=32), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_organizations_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_industry_sector'), ['industry_sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_verification_status'), ['verification_status'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('jti_hash', name=op.f('uq_refresh_tokens_jti_hash'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('user_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('PASSWORD_RESET', 'EMAIL_VERIFICATION', name='usertokenpurpose', native_enum=False, length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_tokens_token_hash'))
    )
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_audit_logs_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)

    op.create_table('facilities',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='facilitystatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_facilities_location_id_locations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_facilities_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facilities'))
    )
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facilities_organization_id'), ['organization_id'], unique=False)

    op.create_table('organization_members',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'MEMBER', 'VIEWER', name='memberrole', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INVITED', 'REVOKED', name='memberstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_members_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_org_member')
    )
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_members_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_members_user_id'), ['user_id'], unique=False)

    op.create_table('requirements',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('intended_application_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_required', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'TONNE', 'LITRE', 'M3', 'KWH', 'MWH', 'GJ', 'UNIT', name='quantityunit', native_enum=False, length=32), nullable=False),
    sa.Column('frequency', sa.Enum('ONE_TIME', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='frequency', native_enum=False, length=32), nullable=False),
    sa.Column('required_from', sa.Date(), nullable=False),
    sa.Column('required_until', sa.Date(), nullable=True),
    sa.Column('max_transport_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('processing_capabilities', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('acceptable_categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('excluded_material_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('virgin_material_price_per_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('max_price_per_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('economic_constraints', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'EXPIRED', 'FULFILLED', 'ARCHIVED', name='listingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('max_price_per_unit IS NULL OR max_price_per_unit >= 0', name=op.f('ck_requirements_max_price_nonneg')),
    sa.CheckConstraint('max_transport_distance_km IS NULL OR max_transport_distance_km > 0', name=op.f('ck_requirements_distance_positive')),
    sa.CheckConstraint('quantity_required > 0', name=op.f('ck_requirements_quantity_positive')),
    sa.CheckConstraint('required_until IS NULL OR required_until >= required_from', name=op.f('ck_requirements_required_order')),
    sa.CheckConstraint('virgin_material_price_per_unit IS NULL OR virgin_material_price_per_unit >= 0', name=op.f('ck_requirements_virgin_price_nonneg')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_requirements_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_requirements_facility_id_facilities')),
    sa.ForeignKeyConstraint(['intended_application_id'], ['application_types.id'], name=op.f('fk_requirements_intended_application_id_application_types')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_requirements_material_id_materials')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_requirements_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements'))
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_intended_application_id'), ['intended_application_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_status'), ['status'], unique=False)
        batch_op.create_index('ix_requirements_status_material', ['status', 'material_id'], unique=False)
        batch_op.create_index('ix_requirements_window', ['required_from', 'required_until'], unique=False)

    op.create_table('resources',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity_available', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'TONNE', 'LITRE', 'M3', 'KWH', 'MWH', 'GJ', 'UNIT', name='quantityunit', native_enum=False, length=32), nullable=False),
    sa.Column('frequency', sa.Enum('ONE_TIME', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='frequency', native_enum=False, length=32), nullable=False),
    sa.Column('availability_start', sa.Date(), nullable=False),
    sa.Column('availability_end', sa.Date(), nullable=True),
    sa.Column('physical_state', sa.Enum('SOLID', 'LIQUID', 'GAS', 'SLUDGE', 'ENERGY', 'OTHER', name='physicalstate', native_enum=False, length=32), nullable=False),
    sa.Column('processing_required', sa.Boolean(), nullable=False),
    sa.Column('processing_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('processing_description', sa.Text(), nullable=True),
    sa.Column('storage_notes', sa.Text(), nullable=True),
    sa.Column('current_use', sa.Text(), nullable=True),
    sa.Column('current_disposition', sa.Enum('DISPOSAL', 'STORAGE', 'INTERNAL_USE', 'LOW_VALUE_USE', 'OTHER', name='currentdisposition', native_enum=False, length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('disposal_cost_per_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('asking_price_per_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('processing_cost_per_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'EXPIRED', 'FULFILLED', 'ARCHIVED', name='listingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('embedding', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('asking_price_per_unit IS NULL OR asking_price_per_unit >= 0', name=op.f('ck_resources_asking_price_nonneg')),
    sa.CheckConstraint('availability_end IS NULL OR availability_end >= availability_start', name=op.f('ck_resources_availability_order')),
    sa.CheckConstraint('disposal_cost_per_unit IS NULL OR disposal_cost_per_unit >= 0', name=op.f('ck_resources_disposal_cost_nonneg')),
    sa.CheckConstraint('processing_cost_per_unit IS NULL OR processing_cost_per_unit >= 0', name=op.f('ck_resources_processing_cost_nonneg')),
    sa.CheckConstraint('quantity_available > 0', name=op.f('ck_resources_quantity_positive')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_resources_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], name=op.f('fk_resources_facility_id_facilities')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_resources_material_id_materials')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_resources_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index('ix_resources_availability', ['availability_start', 'availability_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_facility_id'), ['facility_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_status'), ['status'], unique=False)
        batch_op.create_index('ix_resources_status_material', ['status', 'material_id'], unique=False)

    op.create_table('requirement_property_constraints',
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('min_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('text_value', sa.String(length=255), nullable=True),
    sa.Column('importance', sa.Enum('REQUIRED', 'PREFERRED', 'OPTIONAL', name='propertyimportance', native_enum=False, length=32), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('min_value IS NULL OR max_value IS NULL OR min_value <= max_value', name=op.f('ck_requirement_property_constraints_range_order')),
    sa.ForeignKeyConstraint(['property_id'], ['property_definitions.id'], name=op.f('fk_requirement_property_constraints_property_id_property_definitions')),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_property_constraints_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_property_constraints')),
    sa.UniqueConstraint('requirement_id', 'property_id', name='uq_requirement_property')
    )
    with op.batch_alter_table('requirement_property_constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_property_constraints_requirement_id'), ['requirement_id'], unique=False)

    op.create_table('resource_property_values',
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('property_id', sa.Uuid(), nullable=False),
    sa.Column('value_numeric', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('value_text', sa.String(length=255), nullable=True),
    sa.Column('source', sa.Enum('USER_INPUT', 'AI_EXTRACTED', 'DOCUMENT_VERIFIED', name='valuesource', native_enum=False, length=32), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('provenance', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['property_definitions.id'], name=op.f('fk_resource_property_values_property_id_property_definitions')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_property_values_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_property_values')),
    sa.UniqueConstraint('resource_id', 'property_id', name='uq_resource_property')
    )
    with op.batch_alter_table('resource_property_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_property_values_resource_id'), ['resource_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_property_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_property_values_resource_id'))

    op.drop_table('resource_property_values')
    with op.batch_alter_table('requirement_property_constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_property_constraints_requirement_id'))

    op.drop_table('requirement_property_constraints')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index('ix_resources_status_material')
        batch_op.drop_index(batch_op.f('ix_resources_status'))
        batch_op.drop_index(batch_op.f('ix_resources_organization_id'))
        batch_op.drop_index(batch_op.f('ix_resources_material_id'))
        batch_op.drop_index(batch_op.f('ix_resources_facility_id'))
        batch_op.drop_index('ix_resources_availability')

    op.drop_table('resources')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index('ix_requirements_window')
        batch_op.drop_index('ix_requirements_status_material')
        batch_op.drop_index(batch_op.f('ix_requirements_status'))
        batch_op.drop_index(batch_op.f('ix_requirements_organization_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_material_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_intended_application_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_facility_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('organization_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_organization_members_organization_id'))

    op.drop_table('organization_members')
    with op.batch_alter_table('facilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facilities_organization_id'))

    op.drop_table('facilities')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index('ix_audit_logs_entity')
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tokens_user_id'))

    op.drop_table('user_tokens')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_verification_status'))
        batch_op.drop_index(batch_op.f('ix_organizations_industry_sector'))
        batch_op.drop_index(batch_op.f('ix_organizations_display_name'))

    op.drop_table('organizations')
    with op.batch_alter_table('material_properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_properties_material_id'))

    op.drop_table('material_properties')
    with op.batch_alter_table('material_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_applications_material_id'))
        batch_op.drop_index(batch_op.f('ix_material_applications_application_type_id'))

    op.drop_table('material_applications')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('property_definitions')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_subcategory'))
        batch_op.drop_index(batch_op.f('ix_materials_category'))

    op.drop_table('materials')
    op.drop_table('locations')
    op.drop_table('application_types')
    # ### end Alembic commands ###
