"""connections messaging documents exchanges notifications

Revision ID: 06d349a24ae5
Revises: e2d9d6f7b42a
Create Date: 2026-09-26 11:40:19.347150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (used by JSONB variants in autogenerated code)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06d349a24ae5'
down_revision: Union[str, Sequence[str], None] = 'e2d9d6f7b42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_push_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_push_tokens_token'))
    )
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('NEW_MATCH', 'CONNECTION_REQUEST', 'CONNECTION_ACCEPTED', 'CONNECTION_REJECTED', 'NEW_MESSAGE', 'RESOURCE_EXPIRING', 'REQUIREMENT_EXPIRING', 'LISTING_EXPIRED', 'EXCHANGE_STATUS_CHANGED', name='notificationtype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notifications_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index('ix_notifications_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('connections',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('initiated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('initiated_by_org_id', sa.Uuid(), nullable=False),
    sa.Column('provider_org_id', sa.Uuid(), nullable=False),
    sa.Column('demander_org_id', sa.Uuid(), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'REVOKED', 'EXPIRED', name='connectionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('responded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('response_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['demander_org_id'], ['organizations.id'], name=op.f('fk_connections_demander_org_id_organizations')),
    sa.ForeignKeyConstraint(['initiated_by_org_id'], ['organizations.id'], name=op.f('fk_connections_initiated_by_org_id_organizations')),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], name=op.f('fk_connections_initiated_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_connections_match_id_matches')),
    sa.ForeignKeyConstraint(['provider_org_id'], ['organizations.id'], name=op.f('fk_connections_provider_org_id_organizations')),
    sa.ForeignKeyConstraint(['responded_by_user_id'], ['users.id'], name=op.f('fk_connections_responded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections'))
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_demander_org_id'), ['demander_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_match_id'), ['match_id'], unique=False)
        batch_op.create_index('ix_connections_match_status', ['match_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_provider_org_id'), ['provider_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_status'), ['status'], unique=False)

    op.create_table('exchanges',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('provider_org_id', sa.Uuid(), nullable=False),
    sa.Column('demander_org_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('upstream_exchange_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('agreed_quantity', sa.Numeric(precision=16, scale=3), nullable=False),
    sa.Column('unit', sa.Enum('KG', 'TONNE', 'LITRE', 'M3', 'KWH', 'MWH', 'GJ', 'UNIT', name='quantityunit', native_enum=False, length=32), nullable=False),
    sa.Column('agreed_frequency', sa.Enum('ONE_TIME', 'DAY', 'WEEK', 'MONTH', 'YEAR', name='frequency', native_enum=False, length=32), nullable=False),
    sa.Column('agreed_price_per_unit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('delivery_terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'PAUSED', 'COMPLETED', 'CANCELLED', 'FAILED', name='exchangestatus', native_enum=False, length=32), nullable=False),
    sa.Column('delivered_quantity', sa.Numeric(precision=16, scale=3), nullable=True),
    sa.Column('status_reason', sa.String(length=500), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('agreed_quantity > 0', name=op.f('ck_exchanges_quantity_positive')),
    sa.CheckConstraint('delivered_quantity IS NULL OR delivered_quantity >= 0', name=op.f('ck_exchanges_delivered_nonneg')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name=op.f('ck_exchanges_date_order')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_exchanges_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['demander_org_id'], ['organizations.id'], name=op.f('fk_exchanges_demander_org_id_organizations')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_exchanges_match_id_matches')),
    sa.ForeignKeyConstraint(['provider_org_id'], ['organizations.id'], name=op.f('fk_exchanges_provider_org_id_organizations')),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_exchanges_requirement_id_requirements')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_exchanges_resource_id_resources')),
    sa.ForeignKeyConstraint(['upstream_exchange_id'], ['exchanges.id'], name=op.f('fk_exchanges_upstream_exchange_id_exchanges')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchanges'))
    )
    with op.batch_alter_table('exchanges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exchanges_demander_org_id'), ['demander_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchanges_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchanges_provider_org_id'), ['provider_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exchanges_status'), ['status'], unique=False)

    op.create_table('conversations',
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='conversationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_conversations_connection_id_connections')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_conversations_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('connection_id', name=op.f('uq_conversations_connection_id'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_match_id'), ['match_id'], unique=False)

    op.create_table('conversation_participants',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_participants_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversation_participants_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_participants')),
    sa.UniqueConstraint('conversation_id', 'organization_id', name='uq_conversation_org')
    )
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_participants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_participants_organization_id'), ['organization_id'], unique=False)

    op.create_table('documents',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('requirement_id', sa.Uuid(), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('scan_status', sa.Enum('NOT_SCANNED', 'CLEAN', 'INFECTED', name='scanstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('file_size > 0', name=op.f('ck_documents_size_positive')),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_documents_conversation_id_conversations')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations')),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_documents_requirement_id_requirements')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_documents_resource_id_resources')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_documents_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_resource_id'), ['resource_id'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_user_id', sa.Uuid(), nullable=True),
    sa.Column('sender_organization_id', sa.Uuid(), nullable=True),
    sa.Column('message_type', sa.Enum('TEXT', 'DOCUMENT', 'SYSTEM', 'STRUCTURED_UPDATE', name='messagetype', native_enum=False, length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_messages_document_id_documents')),
    sa.ForeignKeyConstraint(['sender_organization_id'], ['organizations.id'], name=op.f('fk_messages_sender_organization_id_organizations')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_messages_sender_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_conversation_created', ['conversation_id', 'created_at'], unique=False)

    op.create_table('read_receipts',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_read_receipts_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_read_receipts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_read_receipts')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_read_receipt')
    )
    with op.batch_alter_table('read_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_read_receipts_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_read_receipts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('read_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_read_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_read_receipts_message_id'))

    op.drop_table('read_receipts')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_conversation_created')

    op.drop_table('messages')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_resource_id'))
        batch_op.drop_index(batch_op.f('ix_documents_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_documents_organization_id'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_documents_conversation_id'))

    op.drop_table('documents')
    with op.batch_alter_table('conversation_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_participants_organization_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_participants_conversation_id'))

    op.drop_table('conversation_participants')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_match_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('exchanges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exchanges_status'))
        batch_op.drop_index(batch_op.f('ix_exchanges_provider_org_id'))
        batch_op.drop_index(batch_op.f('ix_exchanges_match_id'))
        batch_op.drop_index(batch_op.f('ix_exchanges_demander_org_id'))

    op.drop_table('exchanges')
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_status'))
        batch_op.drop_index(batch_op.f('ix_connections_provider_org_id'))
        batch_op.drop_index('ix_connections_match_status')
        batch_op.drop_index(batch_op.f('ix_connections_match_id'))
        batch_op.drop_index(batch_op.f('ix_connections_demander_org_id'))

    op.drop_table('connections')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_user_created')
        batch_op.drop_index(batch_op.f('ix_notifications_dedupe_key'))

    op.drop_table('notifications')
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_tokens_user_id'))

    op.drop_table('push_tokens')
    # ### end Alembic commands ###
