"""impact records

Revision ID: df269514dda0
Revises: 06d349a24ae5
Create Date: 2026-09-26 11:53:29.562248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (used by JSONB variants in autogenerated code)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df269514dda0'
down_revision: Union[str, Sequence[str], None] = '06d349a24ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impact_records',
    sa.Column('exchange_id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('provider_org_id', sa.Uuid(), nullable=False),
    sa.Column('demander_org_id', sa.Uuid(), nullable=False),
    sa.Column('metric_type', sa.Enum('WASTE_DIVERTED', 'VIRGIN_MATERIAL_AVOIDED', 'TRANSPORT_EMISSIONS', 'PROCESSING_EMISSIONS', 'NET_CO2E', 'ECONOMIC_VALUE', 'ENERGY_RECOVERED', 'OTHER', name='metrictype', native_enum=False, length=32), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('calculation_method', sa.String(length=64), nullable=False),
    sa.Column('methodology_version', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('SYSTEM_ESTIMATE', 'USER_INPUT', 'VERIFIED_OUTCOME', name='impactsource', native_enum=False, length=32), nullable=False),
    sa.Column('uses_demo_factors', sa.Boolean(), nullable=False),
    sa.Column('assumptions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('verified_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['demander_org_id'], ['organizations.id'], name=op.f('fk_impact_records_demander_org_id_organizations')),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], name=op.f('fk_impact_records_exchange_id_exchanges')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_impact_records_match_id_matches')),
    sa.ForeignKeyConstraint(['provider_org_id'], ['organizations.id'], name=op.f('fk_impact_records_provider_org_id_organizations')),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], name=op.f('fk_impact_records_verified_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impact_records'))
    )
    with op.batch_alter_table('impact_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_records_demander_org_id'), ['demander_org_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_records_exchange_id'), ['exchange_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_records_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_records_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_records_provider_org_id'), ['provider_org_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impact_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_records_provider_org_id'))
        batch_op.drop_index(batch_op.f('ix_impact_records_metric_type'))
        batch_op.drop_index(batch_op.f('ix_impact_records_match_id'))
        batch_op.drop_index(batch_op.f('ix_impact_records_exchange_id'))
        batch_op.drop_index(batch_op.f('ix_impact_records_demander_org_id'))

    op.drop_table('impact_records')
    # ### end Alembic commands ###
