"""ai output logs

Revision ID: 3d80ee69eedf
Revises: df269514dda0
Create Date: 2026-09-26 12:02:34.391728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401  (used by JSONB variants in autogenerated code)
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d80ee69eedf'
down_revision: Union[str, Sequence[str], None] = 'df269514dda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_output_logs',
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('input_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('subject_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_output_logs'))
    )
    with op.batch_alter_table('ai_output_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_output_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_output_logs_feature'), ['feature'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_output_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_output_logs_feature'))
        batch_op.drop_index(batch_op.f('ix_ai_output_logs_created_at'))

    op.drop_table('ai_output_logs')
    # ### end Alembic commands ###
